---
- name: Enumerate all cluster hosts within the hosts file
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s HA Cluster Hosts"
    # yamllint disable rule:line-length
    content: |
      {% for host in groups[microk8s_group_ha] %}
      {{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].ansible_hostname }}
      {% endfor %}
    # yamllint enable rule:line-length
  tags:
    - microk8s
    - microk8s.ha
    - microk8s.ha.hosts

- name: Set master var on all hosts
  ansible.builtin.set_fact:
    microk8s_master: "{{ inventory_hostname }}"
  delegate_to: "{{ microk8s_hosts }}"
  delegate_facts: true
  with_items: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: microk8s_hosts
  when: is_master is defined and (is_master | bool)

- name: Waiting for microk8s to be ready on microk8s host master
  ansible.builtin.command:
    cmd: microk8s status --wait-ready
  when: inventory_hostname in microk8s_master
  changed_when: false

- name: Get microk8s cluster nodes
  ansible.builtin.command:
    cmd: kubectl get nodes --no-headers -o custom-columns=:.metadata.name
  when: inventory_hostname in microk8s_master
  changed_when: false
  register: microk8s_cluster_node

- name: Get the microk8s join command from the microk8s master
  ansible.builtin.shell:
    cmd: >-
      microk8s add-node |
      grep -E -m1 'microk8s join {{ microk8s_ip_regex_ha }}'
  with_items: "{{ ansible_play_hosts | difference(microk8s_master) }}"
  loop_control:
    loop_var: microk8s_join_cmd
  when: inventory_hostname in microk8s_master
  changed_when: false
  register: microk8s_join_command

- name: Join microk8s cluster
  when: inventory_hostname not in microk8s_master
  tags:
    - microk8s
    - microk8s.ha
    - microk8s.ha.join
  block:
    - name: Waiting for microk8s to be ready on microk8s host node
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
      changed_when: false

    - name: Set the microk8s join command on the microk8s node
      ansible.builtin.command:
        cmd: "{{ microk8s_join_cmd.stdout }} --skip-verify"
      with_items: "{{ hostvars[microk8s_master]['microk8s_join_command'].results }}" # yamllint disable-line
      loop_control:
        loop_var: microk8s_join_cmd
      when: inventory_hostname in microk8s_join_cmd.microk8s_join_cmd and inventory_hostname not in hostvars[microk8s_master]['microk8s_cluster_node'].stdout # yamllint disable-line
...
